# Adjusts the project files bundle identifiers and includes signing artifacts

steps:
  # Configure signing for dog-food build
  - script: |
      export PROJ_FILE=$(system.defaultWorkingDirectory)/AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
      sed -i -e '/PRODUCT_BUNDLE_IDENTIFIER =/ s/= .*/= "com.microsoft.azure.communication.ui.calling-df";/' $PROJ_FILE
      
      export PROJ_FILE_COMPOSITE=$(system.defaultWorkingDirectory)/AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
      sed -i -e '/PRODUCT_BUNDLE_IDENTIFIER =/ s/= .*/= "277WSW7QTT.com.microsoft.azure.communication.ui.calling-df"; CODE_SIGNING_REQUIRED = "NO"; CODE_SIGNING_ALLOWED = "NO";/' $PROJ_FILE_COMPOSITE
    
      export CHAT_PROJ_FILE_COMPOSITE=$(system.defaultWorkingDirectory)/AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.xcodeproj/project.pbxproj
      sed -i -e '/PRODUCT_BUNDLE_IDENTIFIER =/ s/= .*/= "277WSW7QTT.com.microsoft.azure.communication.ui.chat-df"; CODE_SIGNING_REQUIRED = "NO"; CODE_SIGNING_ALLOWED = "NO";/' $CHAT_PROJ_FILE_COMPOSITE
    
    displayName: 'Edit Bundle Identifiers in project files'

  - task: InstallAppleCertificate@2
    displayName: 'Install Enterprise certificate'
    inputs:
      certSecureFile: Emlyn-Enterprise-Dev-Cert.p12
      certPwd: '$(P12password)'
      setUpPartitionIdACLForPrivateKey: false

  - task: InstallAppleProvisioningProfile@1
    displayName: 'Install Enterprise provisioning profile'
    inputs:
      provProfileSecureFile: 'ACS-UI-calling-df-Dev-20231219.mobileprovision'
