platform :ios, '14.0'

workspace 'AzureCommunicationUI'

project 'sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj'
project 'sdk/AzureCommunicationUICalling/AzureCommunicationUIChat.xcodeproj'
project 'AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp.xcodeproj'

def common_pods
  pod 'MicrosoftFluentUI/Avatar_ios', '0.3.9'
  pod 'MicrosoftFluentUI/BottomSheet_ios', '0.3.9'
  pod 'MicrosoftFluentUI/Button_ios', '0.3.9'
  pod 'MicrosoftFluentUI/PopupMenu_ios', '0.3.9'
  pod 'MicrosoftFluentUI/ActivityIndicator_ios', '0.3.9'
  pod 'SwiftLint', '0.42.0'
end

target 'AzureCommunicationUICalling' do
  project 'sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj'
  use_frameworks!
  common_pods
  pod 'AzureCommunicationCalling', '2.2.0'

  target 'AzureCommunicationUICallingTests' do
    # Pods for testing
    pod 'SwiftLint', '0.42.0'
  end
end

target 'AzureCommunicationUIChat' do
  project 'sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.xcodeproj'
  use_frameworks!
  pod 'AzureCommunicationChat', '1.2.0'
  common_pods
  pod 'MicrosoftFluentUI/AvatarGroup_ios', '0.3.9'

  target 'AzureCommunicationUIChatTests' do
    # Pods for testing
    pod 'SwiftLint', '0.42.0'
  end
end

target 'AzureCommunicationUIDemoApp' do
  project 'AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp.xcodeproj'
  use_frameworks!
  pod 'AzureCommunicationCalling', '2.2.0'
  common_pods
  pod 'SwiftLint', '0.42.0'
  pod 'AppCenter/Crashes', '4.4.1'
  
  target 'AzureCommunicationUIDemoAppUITests' do
    # Pods for testing
    pod 'SwiftLint', '0.42.0'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'SwiftLint'
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
      end
    end
    target.build_configurations.each do |config|
        config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
