platform :ios, '13.0'

workspace 'AzureCommunicationUICalling'

project 'AzureCommunicationUICalling.xcodeproj'
project 'AzureCommunicationUICallingDemoApp.xcodeproj'

target 'AzureCommunicationUICalling' do
  project 'AzureCommunicationUICalling.xcodeproj'
  use_frameworks!
  pod 'AzureCommunicationCalling', '2.2.0-beta.1'
  pod 'MicrosoftFluentUI/Avatar_ios', '0.3.9'
  pod 'MicrosoftFluentUI/BottomSheet_ios', '0.3.9'
  pod 'MicrosoftFluentUI/Button_ios', '0.3.9'
  pod 'MicrosoftFluentUI/PopupMenu_ios', '0.3.9'
  pod 'MicrosoftFluentUI/ActivityIndicator_ios', '0.3.9'
  pod 'SwiftLint', '0.42.0'

  target 'AzureCommunicationUICallingTests' do
    # Pods for testing
    pod 'SwiftLint', '0.42.0'
  end
end

target 'AzureCommunicationUICallingDemoApp' do
  project 'AzureCommunicationUICallingDemoApp.xcodeproj'
  use_frameworks!
  pod 'AzureCommunicationCalling', '2.2.0-beta.1'
  pod 'MicrosoftFluentUI/Avatar_ios', '0.3.9'
  pod 'MicrosoftFluentUI/BottomSheet_ios', '0.3.9'
  pod 'MicrosoftFluentUI/Button_ios', '0.3.9'
  pod 'MicrosoftFluentUI/PopupMenu_ios', '0.3.9'
  pod 'MicrosoftFluentUI/ActivityIndicator_ios', '0.3.9'
  pod 'SwiftLint', '0.42.0'
  
  target 'AzureCommunicationUICallingDemoAppUITests' do
    # Pods for testing
    pod 'SwiftLint', '0.42.0'
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'SwiftLint'
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
      end
    end
  end
end
