# CI Pipeline

# Don't run on push to branches
trigger: none

# Only Run on PRs to these branches
pr:
  - main
  - develop
  - release/*
  - feature/*

variables:
  ${{ if contains(variables['system.pullRequest.targetBranch'], 'chat') }}:
    buildChat: true
  buildChat: false
  
jobs:
  - template: jobs/CI-build-job.yml
