# CI Pipeline

# Don't run on push to branches
trigger: none

# Only Run on PRs to these branches
pr:
  - main
  - develop
  - release/*
  - feature/*

jobs:
  - template: jobs/CI-build-job.yml
    parameters:
      buildChat: $[ or( eq(variables['system.pullRequest.targetBranch'], 'feature/chat'), or(contains(variables['system.pullRequest.sourceBranch'], 'chat'), contains(variables['system.pullRequest.sourceBranch'], 'Chat')) ) ]
