# CI Pipeline

# Don't run on push to branches
trigger: none

# Only Run on PRs to these branches
pr:
  - main
  - develop
  - release/*
  - feature/*

resources:
  repositories:
  - repository: ic3Pipelines
    type: git
    name: ES/internal_build_ic3pt
    ref: refs/tags/release

parameters:
- name: pools
  type: object
  default:
  - name: vsts-mac-142-xcode-152
    os: macos
extends:

  template: v1/IC3.Official.PipelineTemplate.yml@ic3Pipelines
  parameters:
    pool:
      os: windows
      image: windows-2022
      name: Azure-Pipelines-1ESPT-ExDShared
    sdl:
      suppression:
        suppressionFile: $(Build.SourcesDirectory)\guardian\SDL\.gdnsuppress
    stages:
    - stage: Stage
      jobs:
      - job: Job
      - template: eng/pipelines/jobs/CI-build-job.yml@self
