# CI Pipeline

schedules:
  - cron: "0 0 * * *"  # Nightly at midnight
    displayName: "Nightly Build"
    branches:
      include:
        - develop

# Run on pushes to these branches
trigger:
  branches:
    include:
      - main
      - develop
      - release/*
      - feature/*
      - emlyn/ci-yaml-nightly-job

# Run on PRs to these branches
pr:
  - main
  - develop
  - release/*
  - feature/chat

variables:
  targetingChatBranch: $[ eq(variables['System.PullRequest.TargetBranch'], 'feature/chat') ]
  isChatFeature: $[ or(contains(variables['Build.SourceBranch'], 'chat'), contains(variables['Build.SourceBranch'], 'Chat')) ]
  buildChat: or($(isChatFeature), $(targetingChatBranch))

jobs:
  - template: CI-build.yml

  # - job: RunUITests
  #   displayName: "Run UI Tests"
  #   pool:
  #     name: vsts-mac-1231-xcode-1331
  #     demands: xcode
  #   steps:
  #     - task: servicetree-link-build-task@1
  #       displayName: "ServiceTree: [$(BuildOutputUsage)] "
  #       inputs:
  #         ServiceTreeGateway: "ServiceTree Gateway"
  #         Service: "e38fcba7-191b-47ad-bb71-aeff7c983e3f"
  #       condition: always()

    
