# Jazzy Docs Pipeline

# Manual runs only
trigger: none

parameters:
  - name: TargetProject
    type: string
    values:
      - AzureCommunicationUICalling
      - AzureCommunicationUIChat
    default: 'AzureCommunicationUIChat'

jobs:
  - job: BuildJazzy
    displayName: "Build API docs with Jazzy Gem"
    pool:
      name: vsts-mac-131-xcode-142
      demands: xcode

    steps:
      - script: |
          gem install jazzy
        displayName: "Install Jazzy Gem"

      - script: |
          JAZZY_CONFIG_FILE=$(system.defaultWorkingDirectory)/eng/jazzy/${{ variables['TargetProject'] }}.yml
          jazzy --config $JAZZY_CONFIG_FILE
        displayName: "Run Jazzy on $(TargetProject)"
        workingDirectory: AzureCommunicationUI/sdk/${{ variables['TargetProject'] }}

  