# Jazzy Docs Pipeline
resources:
  repositories:
  - repository: internal_tools_acs-mobile-ui # In a different organization
    type: git
    name: SCC/internal_tools_acs-mobile-ui
# Manual runs only
trigger: none

parameters:
  - name: TargetProject
    type: string
    values:
      - AzureCommunicationUICalling
      - AzureCommunicationUIChat
    default: 'AzureCommunicationUIChat'

jobs:
  - job: BuildJazzy
    displayName: "Build API docs with Jazzy Gem"
    pool:
      name: vsts-mac-1231-xcode-1331
      demands: xcode

    steps:
      # - task: UseRubyVersion@0
      #   inputs:
      #     versionSpec: '>= 1.0'

      # - script: |
      #     gem install jazzy
      #   displayName: "Install Jazzy Gem"
      - checkout: internal_tools_acs-mobile-ui
      - script: ls $(system.defaultWorkingDirectory)
      - script: |
          JAZZY_CONFIG_FILE=$(system.defaultWorkingDirectory)/eng/jazzy/${{ variables['TargetProject'] }}.yml
          jazzy --config $JAZZY_CONFIG_FILE
        displayName: "Run Jazzy on $(TargetProject)"
        workingDirectory: AzureCommunicationUI/sdk/${{ variables['TargetProject'] }}

      # Grab source code of 'acs_ui_api_doc_jazzy' azure function from internal tools repo
      # Auth maybe required?

      # Take Jazzy results and override local copy in 'acs_ui_api_doc_jazzy'

      # Deploy jazzy app
