# Jazzy Docs Pipeline
resources:
  repositories:
  - repository: internal_tools_acs-mobile-ui
    type: git
    name: SCC/internal_tools_acs-mobile-ui
    ref: feature/add-jazzy-function-app
  - repository: communication-ui-library-ios # The name used to reference this repository in the checkout step
    type: github
    endpoint: github.com
    name: Azure/communication-ui-library-ios
    ref: feature/jazzy-docs-pipeline

# Manual runs only
trigger: none

parameters:
  - name: TargetProject
    type: string
    values:
      - AzureCommunicationUICalling
      - AzureCommunicationUIChat
    default: 'AzureCommunicationUIChat'
      
jobs:
    
  - job: BuildJazzy
    displayName: "Build API docs with Jazzy Gem"
    pool:
      name: vsts-mac-1231-xcode-1331
      demands: xcode

    steps:
      # - task: UseRubyVersion@0
      #   inputs:
      #     versionSpec: '>= 1.0'

      # - script: |
      #     gem install jazzy
      #   displayName: "Install Jazzy Gem"
      - script: ls $(Build.SourcesDirectory)
      - script: ls $(system.defaultWorkingDirectory)
      - checkout: internal_tools_acs-mobile-ui
        path: jazzy-app
      - checkout: communication-ui-library-ios
        path: ios-repo
      - script: ls $(system.defaultWorkingDirectory) && ls $(system.defaultWorkingDirectory)/ios-repo && ls $(system.defaultWorkingDirectory)/jazzy-app
      - script: |
          JAZZY_CONFIG_FILE=$(system.defaultWorkingDirectory)/eng/jazzy/${{ variables['TargetProject'] }}.yml
          jazzy --config $JAZZY_CONFIG_FILE
        displayName: "Run Jazzy on $(TargetProject)"
        workingDirectory: AzureCommunicationUI/sdk/${{ variables['TargetProject'] }}


      # Take Jazzy results and override local copy in 'acs_ui_api_doc_jazzy'

      # Deploy jazzy app
