# Nightly Build and Test pipeline

# Need to specifically disable this, else all pushes trigger a CI build
trigger: none
pr: none

# Just want a scheduled run
schedules:
  - cron: "0 8 * * *"  # Nightly at midnight PST
    displayName: "Nightly Build"
    branches:
      include:
        - develop
        - main

  # Disabled until working properly
  # - cron: "0 */2 * * *" # Check the AppCenter build schedule every 2 hours
  #   displayName: "AppCenter UI Test Run Trigger"
  #   branches:
  #     include:
  #       - develop
variables:
  AppCenterDevicesOverride: ''
  buildHourOfDay: $[format('{0:H}', pipeline.startTime)]

jobs:
  # If it's midnight-ish pacific time and it was a scheduled build, then run the UI tests
  - ${{ if and(eq(variables['Build.Reason'], 'Schedule'), eq( variables['buildHourOfDay'], '08')) }}:
    - template: jobs/UI-test-job.yml

  - job: ConfigureDevices
    displayName: "Determine AppCenter device set to use"
    pool:
      name: vsts-mac-1301-xcode-141
      demands: xcode
    steps:
      # Sets the AppCenterDevices variable
      - template: jobs/templates/set-appcenter-devices.yml

  - job: AutomatedUITestWithAppCenter
    dependsOn: ConfigureAppCenterDevices
    displayName: "Run XCUITests on AppCenter with specific devices"
    condition: ne(dependencies.ConfigureDevices.outputs['DetermineDeviceSet.AppCenterDevices'], '')
    pool:
      name: vsts-mac-1301-xcode-141
      demands: xcode

    variables:
      - group: 'SPOOL-Communication-mobileUI'

    steps:
      - template: jobs/appcenter-test-job.yml
        parameters:
          DeviceSet: $[ dependencies.ConfigureDevices.outputs['DetermineDeviceSet.AppCenterDevices'] ]