# Nightly Build Pipeline

# Need to specifically disable this, else all pushes trigger a CI build
trigger: none
pr: none

# Just want a scheduled run
schedules:
  - cron: "0 8 * * *"  # Nightly at midnight PST
    displayName: "Nightly Build"
    branches:
      include:
        - develop
        - main

jobs:
  # - template: jobs/UI-test-job.yml
  - job: AutomatedUITestWithAppCenter
    displayName: "Run XCUITests on AppCenter with specific devices"
    pool:
      name: vsts-mac-1301-xcode-141
      demands: xcode

    variables:
      - group: 'SPOOL-Communication-mobileUI'
      - name: 'AppCenterDevices'
    
    steps:
      - template: jobs/templates/set-appcenter-devices.yml