# UI Test Job

jobs: 
  - job: CallingAutomatedUITest
    displayName: "Calling Automated UI Tests"
    pool:
      name: vsts-mac-1301-xcode-141
      demands: xcode

    variables:
      - group: 'SPOOL-Communication-mobileUI'
      - name: 'acsDisplayName'
        value: 'iOS CI UI Automated Tester'

    steps:
      - task: servicetree-link-build-task@1
        displayName: "ServiceTree: [$(BuildOutputUsage)] "
        inputs:
          ServiceTreeGateway: "ServiceTree Gateway"
          Service: "e38fcba7-191b-47ad-bb71-aeff7c983e3f"
        condition: always()

      - task: CocoaPods@0
        displayName: 'pod install'
        inputs:
          workingDirectory: AzureCommunicationUI
          forceRepoUpdate: true
          projectDirectory: AzureCommunicationUI

      - template: templates/update-demo-app-plist-for-testing.yml

      - task: Xcode@5
        displayName: 'Xcode build'
        inputs:
          configuration: Release
          sdk: iphoneos
          xcWorkspacePath: AzureCommunicationUI/AzureCommunicationUI.xcworkspace
          scheme: AzureCommunicationUICalling
          xcodeVersion: default

      - task: Xcode@5
        displayName: 'Xcode Demo UI test'
        inputs:
          actions: test
          configuration: Debug
          sdk: iphoneos
          xcWorkspacePath: AzureCommunicationUI/AzureCommunicationUI.xcworkspace
          scheme: AzureCommunicationUIDemoApp
          xcodeVersion: default
          destinationPlatformOption: iOS
          destinationSimulators: 'iPhone 14 Pro'
          args: '-verbose'
          publishJUnitResults: true

